apiVersion: v1
kind: Service
metadata:
  name: mydotnetapi-service
spec:
  type: ClusterIP
  selector:
    app: kubernetesdemoapi
  ports:
    - name: http        
      port: 8080    
      targetPort: http  
      protocol: TCP     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kubernetesdemoapi
  namespace: default
  labels:
    app:  kubernetesdemoapi
spec:
  selector:
    matchLabels:
      app: kubernetesdemoapi
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  kubernetesdemoapi
    spec:
      volumes:
        - name:  local-data
          hostPath:
            path:  /data
            type:  DirectoryOrCreate
      containers:
      - name:  kubernetesdemoapi
        image:  kubernetesdemo.api:0.1
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  kubernetesapi