apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  FIRST_NAME: "K8SFromConfigMapFirstName"
  SECOND_NAME: "K8SFromConfigMapSecondName"
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: app:1.0.0
      env:
        - name: APP_NAME
          value: K8S
        - name: TEST_KEY
          value: testowanie!!!
        - name: FIRST_NAME_ENV
          valueFrom:
            configMapKeyRef:
              name: config
              key: FIRST_NAME
      envFrom:
        - configMapRef:
            name:  config
