apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.23.4
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "256Mi"
    - name: echo
      image: busybox:1.28
      command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep 999999']
